### ISSUE TITLE
Setting: Add the ability to set a cap for the Shop and Scrub prices.

### ISSUE THREAD

**Issue by Ethryan** [OoTMM/OoTMM#689] opened 2024-03-11 21:08 UTC
Right now, it goes off the size of the wallets, but it would be useful if you use the Bottomless Wallet, that you have an ability to set the max value for shop prices so that they can't run up to 9999. 

I don't feel like grinding rupees for 45 min to buy 1 item.

**Comment by Onemario1234** [comment] 2024-03-12 03:10
You do know there's a Weighted Random setting that favors lower prices, right?

**Comment by Ethryan** [comment] 2024-03-12 03:53
Yes, but I’ve still gotten prices almost as high as 3 000 - 4 000 even with it set to that when using the Bottomless wallet

**Comment by Onemario1234** [comment] 2024-03-12 04:07
It was updated recently so Weighted Random gives you even lower prices, and every seed I've played since that update has had no prices higher than like 1,300.

**Comment by Ethryan** [comment] 2024-03-12 04:21
If thats true then this could probably be closed, it would still be a nice to have feature to have. 
But maybe a low priority thing.

**Comment by Revvenn** [comment] 2024-03-13 15:44
Random Weighted never goes as high as 9,999 and never has. Random (not weighted) has a cap of 5,000. Random Weighted in general has never been as high as the prices you've described either. The highest the old weighting ever went to that I saw for anyone was like 1.9k and most prices hovered around 700-1.3k. Either way, when you factor in your max is 9,999 and you get prices that are at 1k that _considerably lower_ in a relative sense (since the max is 9,999). But people still complained over time so Nax had adjusted it a month ago or so. Prices when you select Random **Weighted** are more balanced now. If you select **Random** it will still be the same as before. Random is what you sign up for when you get it, it's random.

So seeing as your suggestion is largely mitigated by a setting that already exists I'm going to close this but also for future reference, we have a discord and that's where suggestions from players should generally be posted first. One, because of cases like this where you weren't aware of a setting that already exists. And two, because the github is primarily for **confirmed** ideas/suggestions/plans for things that are going to happen and roughly are approved by Nax in one way or another (or just, generally, going to happen because the solo randomizers have them).

**Closed by Revvenn** 2024-03-13 15:44 UTC
