### ISSUE TITLE
Bug: With Master Sword Shuffle Off (maybe can happen even when On?), it is possible to walk past the Master Sword trigger and not be able to get it

### ISSUE THREAD

**Issue by Revvenn** [OoTMM/OoTMM#685] opened 2024-03-02 21:47 UTC
Title is self-explanatory. Today in a seed I started playing, I walked past... like *TO THE RIGHT* slightly from the giving the Master Sword item, you not only will not receive the Master Sword but you'll also just ... NOT be able to get it. Clip below.

https://clips.twitch.tv/ObedientSpinelessPuppyDAESuppy-xkpmJLGZs8plFO0U

I tried leaving ToT entirely and coming back, it still did not give me the Master Sword. How I know the check worked fine for this seed was when I restarted a new file entirely and just went to the *right spot* for the Master Sword and I got it. So. Whatever I did in the above clip that caused me to permanently *miss* the Master Sword needs to be fixed asap lol.

**Comment by Nax** [comment] 2024-03-28 17:17
Can't seem to reproduce that, might have been flag corruption?

**Comment by Revvenn** [comment] 2024-04-03 03:59
Yeah this might have been save corruption without me knowing, it happening so early just seemed like it was so certain it was because of how I missed the trigger for the Master Sword. I'll close this in like, 2 more weeks if I don't have any save corruption issues and if I don't have it come up again.

**Comment by Nax** [comment] 2024-04-14 10:44
Closing as I can't reproduce and you don't seem to have run into it again - feel free to reopen if it occurs again

**Closed by Nax** 2024-04-14 10:44 UTC
Labels: Bug
