### ISSUE TITLE
Setting: Don Gero's Mask in OOT + Shared Don Gero's Mask

### ISSUE THREAD

**Issue by SuperBro64** [OoTMM/OoTMM#656] opened 2024-02-07 23:05 UTC
An idea I had after seeing the other suggestions for masks existing in the opposite game. Basically, until you obtain and are wearing Don Gero's Mask in OoT, you cannot play any songs for the frogs in Zora's River, locking you out of their item checks.

As of right now, this would only lock the two frog Heart Piece checks, but this setting could become more interesting when the frog Purple Rupees get shuffled, also. (https://github.com/OoTMM/OoTMM/issues/154)

When you don't have Don Gero's Mask, the text box that appears when standing on the log that says "Some frogs are looking at you from underwater" could be changed to something else indicating that you need the mask, like "We are waiting for Don Gero to return".

**Comment by Revvenn** [comment] 2024-02-10 15:39
So while the idea sounds good on paper (I'm _kind_ of a fan of it just because it does at least try to make it make sense in how it could be used in OOT), I'm not sure if it's something people would necessarily desire and as you said it would only (right now) lock two checks. Generally, the way we are handling issues/suggestions on the github are for **confirmed** issues/suggestions. The Discord: https://discord.gg/4QdtPBP6wf is where suggestions from users go first to get a feel for whether or not A. it's feasible as an idea to develop (so some devs can see it/give opinion on it)  B. if people want it/desire it and C. if it fits within the scope/design of the randomizer (because yes, some ideas can be considered outside the scope or too romhack-y so on and so forth).

So while I would be glad to keep this up here because _it is_ a decent idea, I have to follow what the rules have been set up as to keep the git as clean as possible (so there's a decent roadmap of things Nax or other devs can **see** and the git doesn't get flooded with people adding things that aren't actually planned). And so I have to close this for right now. You are free to make your suggestion as a thread on the discord and see what people's reactions are to it, however, and we will go from there.

**Closed by Revvenn** 2024-02-10 15:39 UTC
